#!/bin/sh -e
max_args=1024
ns=_v_hack_count_

# Generate descending sequences of comma-separated numbers and arguments from max_args to 0
num_seq=
arg_seq=
n="$max_args"
while [ "$n" -gt 0 ]; do
	num_seq+="$(( --n )), "
	arg_seq+="_$n, "
done
# Strip the trailing commas
num_seq="${num_seq%', '}"
arg_seq="${arg_seq%', '}"

# Output the code
echo "// Generated by scripts/vhacks/count.sh through SHCP. See the Makefile and scripts/shcp.sh for details."
echo "#define ${ns}impl(...) ${ns}indir(__VA_ARGS__, $num_seq)"
echo "// An extra level of indirection is required to expand the commas passed in the first argument from ${ns}impl"
echo "#define ${ns}indir(...) ${ns}count(__VA_ARGS__)"
echo "#define ${ns}count($arg_seq, ...) _0"
